services:
  dashlet:
    image: jaypel/dashlet:latest
    container_name: dashlet
    ports:
      - "3000:3000"
    volumes:
      # Mount the local config.yaml to allow hot-reloading/editing of config
      - ./app/user/config.yaml:/app/app/user/config.yaml:ro
    restart: unless-stopped
